title: Stel de pinnen in voor meerdere schakelaars
hero_image: images/banner.png
description: Hoe kan je de pinnen voor meerdere schakelaars op je Raspberry Pi Pico instellen
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - 
    title: Stel de pinnen in voor meerdere schakelaars
