title: Set the pins for multiple switches
hero_image: images/banner.png
description: multiple-switches-pins description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
